import type { OllCase } from './types'

/**
 * The 57 OLL cases: every way the last layer can be misoriented once the first
 * two layers are solved, each with the standard algorithm that orients it.
 *
 * Ordered by the conventional OLL number, which is the identity of a case — the
 * shape names below are the usual vocabulary (dot, line, fish, lightning bolt,
 * knight move…) and exist to be read, not to identify. The seven cases whose
 * edges are already oriented keep their long-established individual names
 * (Sune, Anti-Sune, H, Pi, Headlights, Chameleon, Bowtie).
 *
 * ## 2-look OLL
 *
 * `twoLook` follows the usual convention: orient the edges first, then the
 * corners. The edge step is the three cases in which the corners happen to be
 * oriented already — the dot (OLL 20), the L (OLL 28) and the line (OLL 57) —
 * and the corner step is the seven cases in which the edges are (OLL 21 to 27).
 * Ten algorithms in total, all of which appear here unchanged, so a learner can
 * start with the subset and grow into the full table without relearning
 * anything.
 *
 * ## Algorithms
 *
 * Standard, widely used, finger-friendly algorithms, none of which leaves a net
 * whole-cube rotation: the tests in `cfop.test.ts` derive each case from its own
 * algorithm and check the orientation counts recorded here against it, so the
 * families and the counts are verified rather than merely asserted.
 */
export const OLL_CASES: readonly OllCase[] = [
  {
    id: 1,
    name: 'Dot 1',
    family: 'dot',
    algorithm: "R U2 R2 F R F' U2 R' F R F'",
    orientedEdges: 0,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 2,
    name: 'Dot 2',
    family: 'dot',
    algorithm: "F R U R' U' F' f R U R' U' f'",
    orientedEdges: 0,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 3,
    name: 'Dot 3',
    family: 'dot',
    algorithm: "f R U R' U' f' U' F R U R' U' F'",
    orientedEdges: 0,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 4,
    name: 'Dot 4',
    family: 'dot',
    algorithm: "f R U R' U' f' U F R U R' U' F'",
    orientedEdges: 0,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 5,
    name: 'Square 1',
    family: 'square',
    algorithm: "l' U2 L U L' U l",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 6,
    name: 'Square 2',
    family: 'square',
    algorithm: "r U2 R' U' R U' r'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 7,
    name: 'Lightning bolt 1',
    family: 'lightning',
    algorithm: "r U R' U R U2 r'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 8,
    name: 'Lightning bolt 2',
    family: 'lightning',
    algorithm: "l' U' L U' L' U2 l",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 9,
    name: 'Fish 1',
    family: 'fish',
    algorithm: "R U R' U' R' F R2 U R' U' F'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 10,
    name: 'Fish 2',
    family: 'fish',
    algorithm: "R U R' U R' F R F' R U2 R'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 11,
    name: 'Lightning bolt 3',
    family: 'lightning',
    algorithm: "r U R' U R' F R F' R U2 r'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 12,
    name: 'Lightning bolt 4',
    family: 'lightning',
    algorithm: "M' R' U' R U' R' U2 R U' M",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 13,
    name: 'Knight move 1',
    family: 'knight',
    algorithm: "r U' r' U' r U r' F' U F",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 14,
    name: 'Knight move 2',
    family: 'knight',
    algorithm: "R' F R U R' F' R F U' F'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 15,
    name: 'Knight move 3',
    family: 'knight',
    algorithm: "l' U' l L' U' L U l' U l",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 16,
    name: 'Knight move 4',
    family: 'knight',
    algorithm: "r U r' R U R' U' r U' r'",
    orientedEdges: 2,
    orientedCorners: 1,
    twoLook: null,
  },
  {
    id: 17,
    name: 'Dot 5',
    family: 'dot',
    algorithm: "R U R' U R' F R F' U2 R' F R F'",
    orientedEdges: 0,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 18,
    name: 'Dot 6',
    family: 'dot',
    algorithm: "r U R' U R U2 r2 U' R U' R' U2 r",
    orientedEdges: 0,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 19,
    name: 'Dot 7',
    family: 'dot',
    algorithm: "M U R U R' U' M' R' F R F'",
    orientedEdges: 0,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 20,
    name: 'Dot 8',
    family: 'dot',
    algorithm: "M U R U R' U' M2 U R U' r'",
    orientedEdges: 0,
    orientedCorners: 4,
    twoLook: 'edge-orientation',
  },
  {
    id: 21,
    name: 'H',
    family: 'cross',
    algorithm: "R U2 R' U' R U R' U' R U' R'",
    orientedEdges: 4,
    orientedCorners: 0,
    twoLook: 'corner-orientation',
  },
  {
    id: 22,
    name: 'Pi',
    family: 'cross',
    algorithm: "R U2 R2 U' R2 U' R2 U2 R",
    orientedEdges: 4,
    orientedCorners: 0,
    twoLook: 'corner-orientation',
  },
  {
    id: 23,
    name: 'Headlights',
    family: 'cross',
    algorithm: "R2 D R' U2 R D' R' U2 R'",
    orientedEdges: 4,
    orientedCorners: 2,
    twoLook: 'corner-orientation',
  },
  {
    id: 24,
    name: 'Chameleon',
    family: 'cross',
    algorithm: "r U R' U' r' F R F'",
    orientedEdges: 4,
    orientedCorners: 2,
    twoLook: 'corner-orientation',
  },
  {
    id: 25,
    name: 'Bowtie',
    family: 'cross',
    algorithm: "F' r U R' U' r' F R",
    orientedEdges: 4,
    orientedCorners: 2,
    twoLook: 'corner-orientation',
  },
  {
    id: 26,
    name: 'Anti-Sune',
    family: 'cross',
    algorithm: "R U2 R' U' R U' R'",
    orientedEdges: 4,
    orientedCorners: 1,
    twoLook: 'corner-orientation',
  },
  {
    id: 27,
    name: 'Sune',
    family: 'cross',
    algorithm: "R U R' U R U2 R'",
    orientedEdges: 4,
    orientedCorners: 1,
    twoLook: 'corner-orientation',
  },
  {
    id: 28,
    name: 'Corners oriented 1',
    family: 'corners-oriented',
    algorithm: "r U R' U' r' R U R U' R'",
    orientedEdges: 2,
    orientedCorners: 4,
    twoLook: 'edge-orientation',
  },
  {
    id: 29,
    name: 'Awkward 1',
    family: 'awkward',
    algorithm: "R U R' U' R U' R' F' U' F R U R'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 30,
    name: 'Awkward 2',
    family: 'awkward',
    algorithm: "F R' F R2 U' R' U' R U R' F2",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 31,
    name: 'P shape 1',
    family: 'p',
    algorithm: "R' U' F U R U' R' F' R",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 32,
    name: 'P shape 2',
    family: 'p',
    algorithm: "L U F' U' L' U L F L'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 33,
    name: 'T shape 1',
    family: 't',
    algorithm: "R U R' U' R' F R F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 34,
    name: 'C shape 1',
    family: 'c',
    algorithm: "R U R2 U' R' F R U R U' F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 35,
    name: 'Fish 3',
    family: 'fish',
    algorithm: "R U2 R2 F R F' R U2 R'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 36,
    name: 'W shape 1',
    family: 'w',
    algorithm: "L' U' L U' L' U L U L F' L' F",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 37,
    name: 'Fish 4',
    family: 'fish',
    algorithm: "F R' F' R U R U' R'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 38,
    name: 'W shape 2',
    family: 'w',
    algorithm: "R U R' U R U' R' U' R' F R F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 39,
    name: 'Lightning bolt 5',
    family: 'lightning',
    algorithm: "L F' L' U' L U F U' L'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 40,
    name: 'Lightning bolt 6',
    family: 'lightning',
    algorithm: "R' F R U R' U' F' U R",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 41,
    name: 'Awkward 3',
    family: 'awkward',
    algorithm: "R U R' U R U2 R' F R U R' U' F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 42,
    name: 'Awkward 4',
    family: 'awkward',
    algorithm: "R' U' R U' R' U2 R F R U R' U' F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 43,
    name: 'P shape 3',
    family: 'p',
    algorithm: "F' U' L' U L F",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 44,
    name: 'P shape 4',
    family: 'p',
    algorithm: "F U R U' R' F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 45,
    name: 'T shape 2',
    family: 't',
    algorithm: "F R U R' U' F'",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 46,
    name: 'C shape 2',
    family: 'c',
    algorithm: "R' U' R' F R F' U R",
    orientedEdges: 2,
    orientedCorners: 2,
    twoLook: null,
  },
  {
    id: 47,
    name: 'L shape 1',
    family: 'l-shape',
    algorithm: "F' L' U' L U L' U' L U F",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 48,
    name: 'L shape 2',
    family: 'l-shape',
    algorithm: "F R U R' U' R U R' U' F'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 49,
    name: 'L shape 3',
    family: 'l-shape',
    algorithm: "r U' r2 U r2 U r2 U' r",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 50,
    name: 'L shape 4',
    family: 'l-shape',
    algorithm: "r' U r2 U' r2 U' r2 U r'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 51,
    name: 'Line 1',
    family: 'line',
    algorithm: "f R U R' U' R U R' U' f'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 52,
    name: 'Line 2',
    family: 'line',
    algorithm: "R U R' U R U' B U' B' R'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 53,
    name: 'L shape 5',
    family: 'l-shape',
    algorithm: "l' U2 L U L' U' L U L' U l",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 54,
    name: 'L shape 6',
    family: 'l-shape',
    algorithm: "r U2 R' U' R U R' U' R U' r'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 55,
    name: 'Line 3',
    family: 'line',
    algorithm: "R U2 R2 U' R U' R' U2 F R F'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 56,
    name: 'Line 4',
    family: 'line',
    algorithm: "r U r' U R U' R' U R U' R' r U' r'",
    orientedEdges: 2,
    orientedCorners: 0,
    twoLook: null,
  },
  {
    id: 57,
    name: 'Corners oriented 2',
    family: 'corners-oriented',
    algorithm: "R U R' U' M' U R U' r'",
    orientedEdges: 2,
    orientedCorners: 4,
    twoLook: 'edge-orientation',
  },
]

/** The ten cases that make up 2-look OLL, in the order they are learnt. */
export const TWO_LOOK_OLL_CASES: readonly OllCase[] = OLL_CASES.filter((entry) => entry.twoLook)
